# Generated by Django 2.1.7 on 2019-02-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190217_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Blog',
            new_name='Content',
        ),
    ]
